// Sample-Projects/Angular - SpringBoot/front-end/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit {
  public loginForm: FormGroup;

  constructor(private fb: FormBuilder) {}

  public ngOnInit(): void {
    this.initForm();
  }

  private initForm = () => {
    this.loginForm = this.fb.group({
      userName: new FormControl(null, Validators.required),
      keyword: new FormControl(null, Validators.required),
    });
  };
}

<div class="login">
  <mat-card>
    <mat-card-title class="text-center">Login</mat-card-title>
    <div class="login-form">
      <form [formGroup]="loginForm">
        <div class="mb-3 w-75">
          <label class="form-label">{{ "login.username" | translate }}*</label>

          <input
            type="text"
            placeholder="{{ 'enter' | translate }}{{
              'login.username' | translate
            }}"
            class="form-control"
            formControlName="userName"
            allowChar="AN"
          />
        </div>
        <div class="mb-3 w-75">
          <label class="form-label">{{ "login.keyword" | translate }}*</label>

          <input
            type="password"
            placeholder="{{ 'enter' | translate }}{{
              'login.keyword' | translate
            }}"
            class="form-control"
            formControlName="keyword"
            (paste)="(false)"
          />
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-primary">
            {{ "button.submit" | translate }}
          </button>
          <button type="button" class="btn btn-default ml-2">
            {{ "button.reset" | translate }}
          </button>
        </div>
      </form>
    </div>
  </mat-card>
</div>

// UI/React-JS/sample-project/src/components/login/Login.js
import React from 'react'

function Login() {
    return (
        <>
            
    <form >
    <div class="form-group">
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <label for="userid" >User Id</label>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <input type="text" 
              id="userId" name="userId" required
              class="form-control" 
              maxlength="15" autocomplete="off"
              placeholder="Enter userid" />
          </div>
        </div>
      
        <div class="form-group">
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
              <label for="pwd" >Pwd</label>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                <input type="password" 
                  id="pwd" name="pwd" required
                  class="form-control" 
                  maxlength="15" autocomplete="off"
                  placeholder="Enter pwd" />
              </div>
            </div>
      
      <div class="form-group" align="left">
        <button type="submit" class="btn btn-primary" >Submit</button>
        <button type="button" class="btn btn-default " > Clear</button >
      </div >
    
    </form >
        </>
    )
}

export default Login
