// UI/Angular/angular-concepts/src/app/scripts/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { StateService } from '@uirouter/angular';
import { AuthService } from './../../services/auth.service'
import { UserService } from './../../services/user.service'
import { NavigationService } from './../../services/navigation.service'
import { MenuService } from './../../services/menu.service'
import { User } from './../../models/User';
import { NavLinks } from './../../models/navLinks';
import { NgForm } from '@angular/forms'
import { Menu } from '../../models/Menu';

@Component({
  templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit {

  user:User;
  login:any = {};
  
    

  constructor(private state: StateService, private authService: AuthService, private userService: UserService,
              private navigationService: NavigationService, private menuService: MenuService) { 
    this.login.isSubmitted = false;
  }

  ngOnInit() {
    
  }

  onSubmit(form : NgForm){
    this.login.isSubmitted = true;
    if(form.valid){
      this.authService.setIsLoggedIn(true);
      this.user = new User();
      this.user.setUserId(this.login.userId);
      this.userService.setUser(this.user);
      let tabId:any[] = [0,1,2,3,4];
      let menuList:NavLinks[] = this.navigationService.getUserMenuList(tabId);
      let menu:Menu = new Menu();
      menu.setMenuList(menuList);
      this.menuService.setMenu(menu);
      this.state.go("user.home");
    }
  }

  clear(): void{
      this.login.userId = "";
      this.login.pwd = "";
  }

}


    <form #loginForm="ngForm">
    <div class="form-group">
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <label for="userid" >User Id</label>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <input type="text" [(ngModel)]="login.userId" #userId="ngModel"
              id="userId" name="userId" required
              class="form-control" noSpecialChar="S"
              maxlength="15" autocomplete="off"
              placeholder="Enter userid" />
          </div>
          <span *ngIf="userId.errors?.required && login.isSubmitted">userid is required</span>
        </div>
      
        <div class="form-group">
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
              <label for="pwd" >Pwd</label>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                <input type="password" [(ngModel)]="login.pwd" #pwd="ngModel"
                  id="pwd" name="pwd" required
                  class="form-control" noSpecialChar (paste)="false"
                  maxlength="15" autocomplete="off"
                  placeholder="Enter pwd" />
              </div>
              <span *ngIf="pwd.errors?.required && login.isSubmitted">pwd is required</span>
            </div>
      
      <div class="form-group" align="left">
        <button type="submit" class="btn btn-primary" (click)="onSubmit(loginForm)">Submit</button>
        <button type="button" class="btn btn-default " (click)="clear()">Clear</button>
      </div>
    
    </form>

// UI/React-JS/sample-project/src/components/login/Login.js
import React from 'react'

function Login() {
    return (
        <>
            
    <form >
    <div class="form-group">
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <label for="userid" >User Id</label>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <input type="text" 
              id="userId" name="userId" required
              class="form-control" 
              maxlength="15" autocomplete="off"
              placeholder="Enter userid" />
          </div>
        </div>
      
        <div class="form-group">
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
              <label for="pwd" >Pwd</label>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                <input type="password" 
                  id="pwd" name="pwd" required
                  class="form-control" 
                  maxlength="15" autocomplete="off"
                  placeholder="Enter pwd" />
              </div>
            </div>
      
      <div class="form-group" align="left">
        <button type="submit" class="btn btn-primary" >Submit</button>
        <button type="button" class="btn btn-default " > Clear</button >
      </div >
    
    </form >
        </>
    )
}

export default Login
